- name: Install MySQL server and client
  apt: pkg={{ item }}
  sudo: yes
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: Change root user password on first run or when mysql.current_root_password was overrided with -e option
  mysql_user:
    login_user=root
    login_password={{ mysql.current_root_password }}
    name=root
    password={{ mysql.root_password }}
    priv=*.*:ALL,GRANT
    host={{ item }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: true

- name: Copy MySQL settings file
  template:
    src=my.cnf.j2
    dest=/etc/mysql/conf.d/my.cnf
    owner=root
    group=root
    mode=0644
  sudo: yes
  notify: mysql-restart

- name: (Re)Create databases
  mysql_db:
    login_user=root
    login_password={{ mysql.root_password }}
    name={{ item }}
    state=present
  with_items: mysql.databases

- name: (Re)Create database users
  mysql_user:
    login_user=root
    login_password={{ mysql.root_password }}
    name={{ item }}
    password={{ mysql.users[item].password }}
    priv={{ mysql.users[item].priv }}
    state={{ mysql.users[item].state | default('present') }}
  with_items: mysql.users|list
