---

- name: Install memcached
  apt: pkg=memcached update_cache=yes
  sudo: yes

- name: Copy memcached configuration file
  template:
    src=memcached.conf.j2
    dest=/etc/memcached.conf
    mode=0644
    owner=root
    group=root
  sudo: yes
  notify: memcached-restart
